resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/91f357abae16099858193b999807323ca9a7c63c/snapshot.yaml
compiler: ghc-8.6.5

packages:
  - cardano-rt-view
  - cardano-tx-generator
  - ext/cardano-node.git/cardano-api
  - ext/cardano-node.git/cardano-cli
  - ext/cardano-node.git/cardano-node
  - ext/cardano-node.git/cardano-config
    #- ext/cardano-db-sync.git/cardano-db
    #- ext/cardano-db-sync.git/cardano-db-sync

local-bin-path: bin

extra-deps:
  - QuickCheck-2.12.6.1
  - Unique-0.4.7.6
  - base58-bytestring-0.1.0
  - bimap-0.4.0
  - binary-0.8.7.0
  - brick-0.47
  - canonical-json-0.6.0.0
  - clock-0.8
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.2
  - directory-1.3.6.1
  - esqueleto-3.2.2
  - generic-monoid-0.1.0.0
  - gray-code-0.3.1
  - hedgehog-1.0.2
  - hspec-2.7.0
  - hspec-core-2.7.0
  - hspec-discover-2.7.0
  - io-streams-1.5.1.0
  - io-streams-haproxy-1.0.1.0
  - micro-recursion-schemes-5.0.2.2
  - moo-1.2
  - network-3.1.1.1
  - persistent-2.10.5.1
  - persistent-postgresql-2.10.1.2
  - persistent-template-2.8.2.3
  - process-1.6.8.2
  - quiet-0.2
  - quickcheck-instances-0.3.19
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1
  - statistics-linreg-0.3
  - streaming-binary-0.3.0.1
  - tasty-hedgehog-1.0.0.2
  - text-1.2.4.0
  - text-zipper-0.10.1
  - th-lift-0.8.1
  - th-lift-instances-0.1.14
  - time-1.8.0.4
  - time-units-1.0.0
  - transformers-except-0.1.1
  - unix-2.7.2.2
  - websockets-0.12.6.1
  - Win32-2.8.5.0
  - word-wrap-0.4.1

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 91f357abae16099858193b999807323ca9a7c63c
    subdirs:
      - .
      - test

#  - git: https://github.com/input-output-hk/cardano-node
#    commit: 376562b0cb6dfde4b9f41e9f3ccea45cbfb41c22
#    subdirs:
#      - cardano-api
#      - cardano-config
#      - cardano-cli
#      - cardano-node

  - git: https://github.com/input-output-hk/cardano-db-sync
    commit: a6e99db3e79036526933aced48c1915b924496c0
    subdirs:
      - cardano-db
      - cardano-db-sync

  - git: https://github.com/input-output-hk/cardano-base
    commit: 2cc27584bb19bd5be9f1721fd4a2393bb99c6119
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 8387be2c5d4f7060a48bceae119973c6382df57c
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 9ee8a6630a8719ba54554c3ce10c555bf5dff4cc
    subdirs:
      - cardano-ledger
      - crypto

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 52afaab4fe99df8fff1e7666e665a923118cfc53
    subdirs:
      # small-steps
      - semantics/executable-spec
      # cs-ledger
      - byron/ledger/executable-spec
      # cs-blockchain
      - byron/chain/executable-spec
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/executable-spec/test

    # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: ec4f3af58c13a4c20116e9e262b048fb2d27bdc3
    subdirs:
        - io-sim
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - ouroboros-consensus-byron
        - ouroboros-consensus-cardano
        - ouroboros-consensus/ouroboros-consensus-mock
        - ouroboros-consensus-shelley
        - typed-protocols
        - typed-protocols-examples
        - ouroboros-network-testing
        - ouroboros-network-framework
        - Win32-network

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 8f7d2a4ba4288e528fea62946b525f493c26ae7a
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/backend-trace-acceptor
      - plugins/backend-trace-forwarder
      - plugins/scribe-systemd
      - tracer-transformers

    # dependencies of iohk-monitoring
  - prometheus-2.1.2
  - libsystemd-journal-1.4.4
  - katip-0.8.4.0

    # Includes updated pretty printing function
  - git: https://github.com/well-typed/cborg.git
    commit: 42a83192749774268337258f4f94c97584b80ca6
    subdirs:
        - cborg

    # Includes a windows build fix (https://github.com/snoyberg/http-client/pull/430)
#  - git: https://github.com/snoyberg/http-client.git
#    commit: 1a75bdfca014723dd5d40760fad854b3f0f37156
#    subdirs:
#        - http-client

nix:
    shell-file: nix/stack-shell.nix
#  pure: true
#  packages: [ zlib.dev, zlib.out
#            , openssl.dev, openssl.out
#            , haskell.compiler.ghc865
#            , pkg-config
#            , systemd.dev
#            , postgresql
#            ]
