# global filter; messages must have at least this severity to pass:
minSeverity: Info

TurnOnLogMetrics: False

# global file rotation settings:
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK
  - LogBufferBK
  - TraceAcceptorBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: StdoutSK
    scName: stdout
    scFormat: ScText
    scRotation: null

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - StdoutSK
    - stdout

# more options which can be passed as key-value pairs:
options:
  mapBackends:
    cardano-rt-view.acceptor:
      - LogBufferBK

# accepting incoming traces and naming them
traceAcceptAt:
  - nodeName: "pool1"
    remoteAddr:
      tag: RemotePipe
      contents: "logs/sockets/pool1"
  - nodeName: "pool2"
    remoteAddr:
      tag: RemotePipe
      contents: "logs/sockets/pool2"
  - nodeName: "pool3"
    remoteAddr:
      tag: RemotePipe
      contents: "logs/sockets/pool3"

