steps:
  - label: 'Chain-sync benchmark Mainnet'
    command:
      - nix-shell -A devops --run "niv update cardano-node"
      - ./benchmarks/chain-sync/ci-full-sync.sh mainnet
      - nix-shell -A devops --run "niv show cardano-node | tee -a benchmark-results.log"
    timeout_in_minutes: 300
    artifact_paths:
      - "benchmark-results.log"
    agents:
      system: x86_64-linux
      queue: benchmark
