steps:
  # - label: hydra-eval-errors
  #   command: 'nix-build ./nix -A iohkNix.hydraEvalErrors && ./result/bin/hydra-eval-errors.py'
  #   agents:
  #     system: x86_64-linux

  - label: 'check-cabal-project'
    command: 'nix-build ./nix -A iohkNix.checkCabalProject -o check-cabal-project.sh && ./check-cabal-project.sh'
    agents:
      system: x86_64-linux

  # - label: Check repo dependency tags are present on master branches
  #   commands:
  #     - "nix build -f ./nix iohkNix.checkRepoTagsOnMasterBranches --arg src ./. --show-trace"
  #   agents:
  #     system: x86_64-linux

  # - label: 'Check Stylish Haskell'
  #   command: 'nix-shell --run ./.buildkite/check-stylish.sh nix/stack-shell.nix'
  #   agents:
  #     system: x86_64-linux
