# global filter; messages must have at least this severity to pass:
minSeverity: Debug

# global file rotation settings:
rotation:
  rpLogLimitBytes: 25000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK
  - TraceForwarderBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# if wanted, the GUI is listening on this port:
#hasGUI: 12871

# if wanted, the EKG interface is listening on this port:
#hasEKG: 12781

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: FileSK
    scName: "logs/node-0.json"
    scFormat: ScJson

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - FileSK
    - "logs/node-0.json"

# more options which can be passed as key-value pairs:
options:
  mapBackends:
    cardano.node.ChainDB.metrics:
      - TraceForwarderBK
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.Forge.metrics:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
      - TraceForwarderBK
    cardano.node-metrics:
      - kind: UserDefinedBK
        name: LiveViewBackend
      - TraceForwarderBK
    cardano.node.metrics:
      - TraceForwarderBK
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.BlockFetchDecision.peers:
      - TraceForwarderBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.release:
      - TraceForwarderBK
    cardano.node.version:
      - TraceForwarderBK
    cardano.node.commit:
      - TraceForwarderBK

traceForwardTo:
  tag: RemotePipe
  contents: "logs/sockets/0"

##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId:
Protocol: RealPBFT
GenesisFile: genesis/genesis.json
NumCoreNodes: 1
RequiresNetworkMagic: RequiresMagic
PBftSignatureThreshold:
TurnOnLogging: True
ViewMode: LiveView
TurnOnLogMetrics: True
SocketPath:



#####    Update Parameters    #####

ApplicationName: cardano-sl
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0

#####         Tracing         #####

# MinimalVerbosity: Minimal level of the rendering of captured items
# MaximalVerbosity: Maximal level of the rendering of captured items
# NormalVerbosity: the default level of the rendering of captured items
TracingVerbosity: MaximalVerbosity

# Trace BlockFetch client.
TraceBlockFetchClient: True

# Trace BlockFetch decisions made by the BlockFetch client.
TraceBlockFetchDecisions: True

# Trace BlockFetch protocol messages.
TraceBlockFetchProtocol: True

# Serialised Trace BlockFetch protocol messages.
TraceBlockFetchProtocolSerialised: False

# Trace BlockFetch server.
TraceBlockFetchServer: True

# Verbose tracer of ChainDB
TraceChainDb: True

# Trace ChainSync client.
TraceChainSyncClient: False

# Trace ChainSync server (blocks).
TraceChainSyncBlockServer: False

# Trace ChainSync server (headers)
TraceChainSyncHeaderServer: False

# Trace ChainSync protocol messages.
TraceChainSyncProtocol: True

# Trace DNS Resolver messages.
TraceDNSResolver: False

# Trace DNS Subscription messages.
TraceDNSSubscription: False

# Trace error policy resolution.
TraceErrorPolicy: False

# Trace local error policy resolution.
TraceLocalErrorPolicy: True

# Trace block forging.
TraceForge: True

# Trace IP Subscription messages.
TraceIpSubscription: False

# Trace local ChainSync protocol messages.
TraceLocalChainSyncProtocol: True

# Trace local TxSubmission protocol messages.
TraceLocalTxSubmissionProtocol: True

# Trace local TxSubmission server.
TraceLocalTxSubmissionServer: True

# Trace mempool.
TraceMempool: True

# Trace Mux Events
TraceMux: False

# Trace TxSubmission server (inbound transactions).
TraceTxInbound: True

# Trace TxSubmission client (outbound transactions).
TraceTxOutbound: True

# Trace TxSubmission protocol messages.
TraceTxSubmissionProtocol: True
