# global filter; messages must have at least this severity to pass:
minSeverity: Debug

# global file rotation settings:
rotation:
  rpLogLimitBytes: 25000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# if wanted, the GUI is listening on this port:
#hasGUI: 12871

# if wanted, the EKG interface is listening on this port:
#hasEKG: 12781

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: FileSK
    scName: "logs/node-2.json"
    scFormat: ScJson
  - scKind: StdoutSK
    scName: "stdout"
    scFormat: ScJson

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - FileSK
    - "logs/node-2.json"
  # - - StdoutSK
  #   - "stdout"

# more options which can be passed as key-value pairs:
options:
  mapSubtrace:
    benchmark:
      contents:
        - GhcRtsStats
        - MonotonicClock
      subtrace: ObservableTrace
    '#ekgview':
      contents:
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: .monoclock.basic.
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.cpuNs.timed.
      - - tag: StartsWith
          contents: '#ekgview.#aggregation.cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.gcNum.timed.
      subtrace: FilterTrace
    'cardano.epoch-validation.utxo-stats':
      # Change the `subtrace` value to `Neutral` in order to log
      # `UTxO`-related messages during epoch validation.
      subtrace: NoTrace
  mapBackends:
    cardano.node.ChainDB.metrics:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.metrics:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.BlockFetchDecision:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.BlockFetchDecision.peers:
      - kind: UserDefinedBK
        name: LiveViewBackend

##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId:
Protocol: RealPBFT
GenesisFile: genesis/genesis.json
NumCoreNodes: 1
RequiresNetworkMagic: RequiresMagic
PBftSignatureThreshold:
TurnOnLogging: True
ViewMode: LiveView
TurnOnLogMetrics: False
SocketPath:



#####    Update Parameters    #####

ApplicationName: cardano-sl
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0

#####         Tracing         #####

# MinimalVerbosity: Minimal level of the rendering of captured items
# MaximalVerbosity: Maximal level of the rendering of captured items
# NormalVerbosity: the default level of the rendering of captured items
TracingVerbosity: NormalVerbosity

TraceBlockFetchClient: True
TraceBlockFetchDecisions: False
TraceBlockFetchProtocol: True
TraceBlockFetchProtocolSerialised: False
TraceBlockFetchServer: False
TraceChainDb: True
TraceChainSyncClient: False
TraceChainSyncBlockServer: False
TraceChainSyncHeaderServer: False
TraceChainSyncProtocol: False
TraceDNSResolver: False
TraceDNSSubscription: False
TraceErrorPolicy: False
TraceForge: False
TraceIpSubscription: False
TraceLocalChainSyncProtocol: True
TraceLocalTxSubmissionProtocol: True
TraceLocalTxSubmissionServer: True
TraceMempool: True
TraceMux: False
TraceTxInbound: True
TraceTxOutbound: True
TraceTxSubmissionProtocol: True
